# spring.application.name=unifiedads
spring.main.web-application-type=none

# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
spring.main.banner-mode=off
logging.pattern.console=${LOGGING_PATTERN_CONSOLE:%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n}

transport.mode=stdio
spring.ai.openai.api-key=YOUR_API_KEY
# logging.file.name=mcp.weather.log